CREATE TABLE debts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount      VARCHAR(255),
    person      VARCHAR(255),
    description VARCHAR(255),
    type        VARCHAR(255),
    status      VARCHAR(255),
    date        date,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_debts PRIMARY KEY (id)
);

CREATE TABLE transactions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    amount      DOUBLE PRECISION,
    type        VARCHAR(255),
    category    VARCHAR(255),
    description VARCHAR(255),
    date        date,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    phone_number  VARCHAR(255),
    email         VARCHAR(255),
    password      VARCHAR(255),
    role          VARCHAR(255),
    registered_at TIMESTAMP WITHOUT TIME ZONE,
    is_active     Boolean,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);


SELECT * FROM users;
